### PR TITLE
#221: defaultMonoidResult is unlawful + #222: add lastQueryResultSemigroup

### LINKED ISSUE #221: defaultMonoidResult is unlawful
failing test case:

```ts
import * as fc from 'fast-check';
import { monoid } from 'fp-ts-laws';
import { getSetoid } from '../src/QueryResult';
import { setoidString, setoidNumber } from 'fp-ts/lib/Setoid';
import { getQueryResult } from './QueryResultArbitrary';
import { defaultMonoidResult } from '../src/react/util';

describe('defaultMonoidResult', () => {
  it('Monoid', () =>
    monoid(
      defaultMonoidResult<string, number>(),
      getSetoid(setoidString, setoidNumber),
      getQueryResult(fc.string(), fc.integer())
    ));
});

```

### LINKED ISSUE #222: add lastQueryResultSemigroup
instead of keeping the last Success or Failure (default as of now), should simply return the latest event

### PR DESCRIPTION
**Pull request by giogonzo**
Closes #221
Closes #222

## Test Plan

see added unit tests

### CODE REVIEW

File: test/QueryResultArbitrary.ts [hunk 1]
```diff
@@ -0,0 +1,31 @@
+import * as fc from 'fast-check';
```
Comment (giogonzo) [inline test/QueryResultArbitrary.ts:1]: this file was only extracted from `QueryResult.test.ts` since it's now reused in two different test files

File: src/react/util.ts [hunk 2]
```diff
@@ -1,11 +0,0 @@
-import { QueryResult, loading, success } from '../QueryResult';
```
Comment (giogonzo) [inline src/react/util.ts:1]: I renamed this file into `Semigroup` since its content is now also exported publicly (see `react/index.ts`)

File: src/react/Semigroup.ts [hunk 3]
```diff
@@ -0,0 +1,19 @@
...
+export function keepQueryResultSemigroup<L, P>(): Semigroup<QueryResult<L, P>> {
+  return {
+    concat: (a, b) =>
+      a.type === 'Success' && b.type === 'Loading'
+        ? success(a.value, true)
+        : a.type === 'Failure' && b.type === 'Loading'
+        ? failure(a.value, true)
+        : b
+  };
+}
```
Comment (aSlug) [inline src/react/Semigroup.ts:13]: `defaultMonoidResult` was keeping the initial result only if it was `success` while `keepQueryResultSemigroup ` keeps it also if it is `failure`. Is it intentional?
Btw to me it looks more correct now but I think its worth to highlight that the behaviour is not the same.

Comment (giogonzo) [reply src/react/Semigroup.ts:13]: > to me it looks more correct now but I think it's worth to highlight that the behaviour is not the same.

yes, same reasoning for me. I applied this change in this PR because it is already breaking in any case. In practice, I doubt there will be any visible effect of this change in our projects, but let's see

**Comment by giogonzo** [comment]
@aSlug I published this branch as `avenger@6.0.0-1`. I would wait for you to test it on the project and see if working as intended before merging & releasing!

**Comment by aSlug** [comment]
@giogonzo it works perfectly! 👍

**Comment by aSlug** [comment]
I think this PR makes the issue https://github.com/buildo/avenger/issues/207 outdated

**Comment by giogonzo** [comment]
@aSlug good point.. I'll leave that issue open for the README/documentation part, but add JSDoc in this PR before merging and releasing

**Comment by giogonzo** [comment]
published `v6.0.0`
