### PR TITLE
#205: Add Query mapLeft (closes #205)

### LINKED ISSUE #205: Add Query mapLeft
While doing some backporting, I came across some instances of `command`s that are:
- failing with a very specific `L`, e.g. `'generic' | 'specific'`
- declaring invalidations on queries that instead fail with a very loose `L`, like `unknown`

E.g.

```ts
declare function addUser: () => TaskEither<'generic' | 'specific', string>
declare const users: ObservableQuery<void, unknown, Array<User>>

const doAddUser = command(addUser, { users })
```
Given how types are written at the moment, the resulting `doAddUser` will return a `TaskEither<unknown, string>` because the resulting `L` is computed as `CmdL | InvaldiationsL`, and `'generic' | 'specific' | unknown` is just = `unknown`

This is desired in general (and you can always spot it downstream when you are not able e.g. to be exhaustive in matching the error). But at the same time, it is currently hard/impossible to make the invalidations `L` more specific without changing the original query logic.

I think adding a `mapLeft` on `Query` would allow to use it inline when needed from command declarations, e.g.:

```ts
const doAddUser = command(addUser, { users: mapLeft(users, () => 'generic') })
```

### PR DESCRIPTION
**Pull request by giogonzo**
Closes #205

## Test Plan

See added unit tests

### tests performed

> A Test Plan is used to show what you tested to make sure your code works fine. You should write here all that you did to test, and provide some results of your testing.

> These results can be screenshots, query results, or even just pointers to unit tests that successfully passed.

### tests not performed (domain coverage)

> At times not everything can be tested, and writing what hasn't been tested is just as important as writing what has been tested.

> An example of partial test is a field displaying 4 possible values. If 3 values are tested, with screenshots, and 1 is not, then it should be mentioned here.

### CODE REVIEW

File: src/Query.ts [hunk 1]
```diff
@@ -202,8 +202,17 @@ export function map<U, L, A, B>(
   fa: ObservableQuery<U, L, A>,
   f: (a: A) => B
 ): ObservableQuery<U, L, B> {
-  return compose(
-    fa,
-    queryStrict(a => taskEither.of<L, B>(f(a)), available)
-  );
+  return queryStrict(a => fa.run(a).map(f), available);
```
Comment (fes300) [inline src/Query.ts]: seeing this I feel the urge to change to name of `compose` to `chain` :D

Comment (giogonzo) [reply src/Query.ts]: 😂 yes I know, even though this is not 100% correct in fp-ts lingo. See my "side note" here: https://github.com/buildo/avenger/issues/201#issuecomment-524835612
